name: GaN 2024 Import (monthly upsert)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 2 * *"   # 05:00 UTC on the 2nd of each month

jobs:
  import-gan-2024:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pandas requests python-dateutil

      - name: Run importer script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
        run: |
          python scripts/fetch_globe_at_night_2024.py