name: GaN 2024 Import (monthly upsert)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # 1st of each month

jobs:
  import-gan-2024:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install pandas requests supabase
      - name: Run import
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          python scripts/fetch_globe_at_night_2024.py
